import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Poster from '../components/Poster/Poster'
import NameFilm from '../components/NameFilm/NameFilm'
import RandomFilmButton from '../components/RandomFilmButton/RandomFilmButton'
import CountrySelect from '../components/CountrySelect'
import GenreSelect from '../components/GenreSelect'
import YearsSlider from '../components/YearsSlider'
import RatingSlider from '../components/RatingSlider'
import { useAppSelector } from '../hooks/redux'
import { kinopoiskSlice } from '../store/kinopoiskSlice'
import { useDispatch } from 'react-redux'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const {error} = useAppSelector(state => state.kinopoisk)
  const {shuffle} = kinopoiskSlice.actions
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(shuffle())
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.container}>
            <div className={styles.filmWrapper}>
              <Poster/>
              <NameFilm/>
            </div>
            <RandomFilmButton/>
            {error && <h2>Ошибка: {error}</h2>}
            {/* Фильтры поиска*/}
            <div className={styles.filtersWrapper}>
              <CountrySelect/>
              <GenreSelect/>
              <YearsSlider/>
              <RatingSlider/>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
